/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AktivitasRouteImport } from './routes/aktivitas'
import { Route as EventRouteImport } from './routes/event'
import { Route as LatihanRouteImport } from './routes/latihan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PengumumanRouteImport } from './routes/pengumuman'
import { Route as PerenangRouteImport } from './routes/perenang'
import { Route as TerimaRouteImport } from './routes/terima'
import { Route as UndanganRouteImport } from './routes/undangan'
import { Route as EventIdRouteImport } from './routes/event_.$id'
import { Route as LatihanIdRouteImport } from './routes/latihan_.$id'
import { Route as LatihanBaruRouteImport } from './routes/latihan_.baru'
import { Route as LatihanJadwalRouteImport } from './routes/latihan_.jadwal'
import { Route as PengumumanIdRouteImport } from './routes/pengumuman_.$id'
import { Route as PerenangIdRouteImport } from './routes/perenang_.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LatihanIdUbahRouteImport } from './routes/latihan_.$id_.ubah'
import { Route as LatihanJadwalUbahRouteImport } from './routes/latihan_.jadwal_.ubah'
import { Route as PerenangIdLaporanRouteImport } from './routes/perenang_.$id_.laporan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivitasRoute = AktivitasRouteImport.update({
  id: '/aktivitas',
  path: '/aktivitas',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanRoute = LatihanRouteImport.update({
  id: '/latihan',
  path: '/latihan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PengumumanRoute = PengumumanRouteImport.update({
  id: '/pengumuman',
  path: '/pengumuman',
  getParentRoute: () => rootRouteImport,
} as any)
const PerenangRoute = PerenangRouteImport.update({
  id: '/perenang',
  path: '/perenang',
  getParentRoute: () => rootRouteImport,
} as any)
const TerimaRoute = TerimaRouteImport.update({
  id: '/terima',
  path: '/terima',
  getParentRoute: () => rootRouteImport,
} as any)
const UndanganRoute = UndanganRouteImport.update({
  id: '/undangan',
  path: '/undangan',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event_/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanIdRoute = LatihanIdRouteImport.update({
  id: '/latihan_/$id',
  path: '/latihan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanBaruRoute = LatihanBaruRouteImport.update({
  id: '/latihan_/baru',
  path: '/latihan/baru',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanJadwalRoute = LatihanJadwalRouteImport.update({
  id: '/latihan_/jadwal',
  path: '/latihan/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const PengumumanIdRoute = PengumumanIdRouteImport.update({
  id: '/pengumuman_/$id',
  path: '/pengumuman/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerenangIdRoute = PerenangIdRouteImport.update({
  id: '/perenang_/$id',
  path: '/perenang/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanIdUbahRoute = LatihanIdUbahRouteImport.update({
  id: '/latihan_/$id_/ubah',
  path: '/latihan/$id/ubah',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanJadwalUbahRoute = LatihanJadwalUbahRouteImport.update({
  id: '/latihan_/jadwal_/ubah',
  path: '/latihan/jadwal/ubah',
  getParentRoute: () => rootRouteImport,
} as any)
const PerenangIdLaporanRoute = PerenangIdLaporanRouteImport.update({
  id: '/perenang_/$id_/laporan',
  path: '/perenang/$id/laporan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktivitas': typeof AktivitasRoute
  '/event': typeof EventRoute
  '/latihan': typeof LatihanRoute
  '/login': typeof LoginRoute
  '/pengumuman': typeof PengumumanRoute
  '/perenang': typeof PerenangRoute
  '/terima': typeof TerimaRoute
  '/undangan': typeof UndanganRoute
  '/event/$id': typeof EventIdRoute
  '/latihan/$id': typeof LatihanIdRoute
  '/latihan/baru': typeof LatihanBaruRoute
  '/latihan/jadwal': typeof LatihanJadwalRoute
  '/pengumuman/$id': typeof PengumumanIdRoute
  '/perenang/$id': typeof PerenangIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/latihan/$id/ubah': typeof LatihanIdUbahRoute
  '/latihan/jadwal/ubah': typeof LatihanJadwalUbahRoute
  '/perenang/$id/laporan': typeof PerenangIdLaporanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktivitas': typeof AktivitasRoute
  '/event': typeof EventRoute
  '/latihan': typeof LatihanRoute
  '/login': typeof LoginRoute
  '/pengumuman': typeof PengumumanRoute
  '/perenang': typeof PerenangRoute
  '/terima': typeof TerimaRoute
  '/undangan': typeof UndanganRoute
  '/event/$id': typeof EventIdRoute
  '/latihan/$id': typeof LatihanIdRoute
  '/latihan/baru': typeof LatihanBaruRoute
  '/latihan/jadwal': typeof LatihanJadwalRoute
  '/pengumuman/$id': typeof PengumumanIdRoute
  '/perenang/$id': typeof PerenangIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/latihan/$id/ubah': typeof LatihanIdUbahRoute
  '/latihan/jadwal/ubah': typeof LatihanJadwalUbahRoute
  '/perenang/$id/laporan': typeof PerenangIdLaporanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktivitas': typeof AktivitasRoute
  '/event': typeof EventRoute
  '/latihan': typeof LatihanRoute
  '/login': typeof LoginRoute
  '/pengumuman': typeof PengumumanRoute
  '/perenang': typeof PerenangRoute
  '/terima': typeof TerimaRoute
  '/undangan': typeof UndanganRoute
  '/event_/$id': typeof EventIdRoute
  '/latihan_/$id': typeof LatihanIdRoute
  '/latihan_/baru': typeof LatihanBaruRoute
  '/latihan_/jadwal': typeof LatihanJadwalRoute
  '/pengumuman_/$id': typeof PengumumanIdRoute
  '/perenang_/$id': typeof PerenangIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/latihan_/$id_/ubah': typeof LatihanIdUbahRoute
  '/latihan_/jadwal_/ubah': typeof LatihanJadwalUbahRoute
  '/perenang_/$id_/laporan': typeof PerenangIdLaporanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktivitas'
    | '/event'
    | '/latihan'
    | '/login'
    | '/pengumuman'
    | '/perenang'
    | '/terima'
    | '/undangan'
    | '/event/$id'
    | '/latihan/$id'
    | '/latihan/baru'
    | '/latihan/jadwal'
    | '/pengumuman/$id'
    | '/perenang/$id'
    | '/api/auth/$'
    | '/latihan/$id/ubah'
    | '/latihan/jadwal/ubah'
    | '/perenang/$id/laporan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktivitas'
    | '/event'
    | '/latihan'
    | '/login'
    | '/pengumuman'
    | '/perenang'
    | '/terima'
    | '/undangan'
    | '/event/$id'
    | '/latihan/$id'
    | '/latihan/baru'
    | '/latihan/jadwal'
    | '/pengumuman/$id'
    | '/perenang/$id'
    | '/api/auth/$'
    | '/latihan/$id/ubah'
    | '/latihan/jadwal/ubah'
    | '/perenang/$id/laporan'
  id:
    | '__root__'
    | '/'
    | '/aktivitas'
    | '/event'
    | '/latihan'
    | '/login'
    | '/pengumuman'
    | '/perenang'
    | '/terima'
    | '/undangan'
    | '/event_/$id'
    | '/latihan_/$id'
    | '/latihan_/baru'
    | '/latihan_/jadwal'
    | '/pengumuman_/$id'
    | '/perenang_/$id'
    | '/api/auth/$'
    | '/latihan_/$id_/ubah'
    | '/latihan_/jadwal_/ubah'
    | '/perenang_/$id_/laporan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktivitasRoute: typeof AktivitasRoute
  EventRoute: typeof EventRoute
  LatihanRoute: typeof LatihanRoute
  LoginRoute: typeof LoginRoute
  PengumumanRoute: typeof PengumumanRoute
  PerenangRoute: typeof PerenangRoute
  TerimaRoute: typeof TerimaRoute
  UndanganRoute: typeof UndanganRoute
  EventIdRoute: typeof EventIdRoute
  LatihanIdRoute: typeof LatihanIdRoute
  LatihanBaruRoute: typeof LatihanBaruRoute
  LatihanJadwalRoute: typeof LatihanJadwalRoute
  PengumumanIdRoute: typeof PengumumanIdRoute
  PerenangIdRoute: typeof PerenangIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  LatihanIdUbahRoute: typeof LatihanIdUbahRoute
  LatihanJadwalUbahRoute: typeof LatihanJadwalUbahRoute
  PerenangIdLaporanRoute: typeof PerenangIdLaporanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivitas': {
      id: '/aktivitas'
      path: '/aktivitas'
      fullPath: '/aktivitas'
      preLoaderRoute: typeof AktivitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan': {
      id: '/latihan'
      path: '/latihan'
      fullPath: '/latihan'
      preLoaderRoute: typeof LatihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengumuman': {
      id: '/pengumuman'
      path: '/pengumuman'
      fullPath: '/pengumuman'
      preLoaderRoute: typeof PengumumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perenang': {
      id: '/perenang'
      path: '/perenang'
      fullPath: '/perenang'
      preLoaderRoute: typeof PerenangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terima': {
      id: '/terima'
      path: '/terima'
      fullPath: '/terima'
      preLoaderRoute: typeof TerimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/undangan': {
      id: '/undangan'
      path: '/undangan'
      fullPath: '/undangan'
      preLoaderRoute: typeof UndanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event_/$id': {
      id: '/event_/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan_/$id': {
      id: '/latihan_/$id'
      path: '/latihan/$id'
      fullPath: '/latihan/$id'
      preLoaderRoute: typeof LatihanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan_/baru': {
      id: '/latihan_/baru'
      path: '/latihan/baru'
      fullPath: '/latihan/baru'
      preLoaderRoute: typeof LatihanBaruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan_/jadwal': {
      id: '/latihan_/jadwal'
      path: '/latihan/jadwal'
      fullPath: '/latihan/jadwal'
      preLoaderRoute: typeof LatihanJadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengumuman_/$id': {
      id: '/pengumuman_/$id'
      path: '/pengumuman/$id'
      fullPath: '/pengumuman/$id'
      preLoaderRoute: typeof PengumumanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perenang_/$id': {
      id: '/perenang_/$id'
      path: '/perenang/$id'
      fullPath: '/perenang/$id'
      preLoaderRoute: typeof PerenangIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan_/$id_/ubah': {
      id: '/latihan_/$id_/ubah'
      path: '/latihan/$id/ubah'
      fullPath: '/latihan/$id/ubah'
      preLoaderRoute: typeof LatihanIdUbahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan_/jadwal_/ubah': {
      id: '/latihan_/jadwal_/ubah'
      path: '/latihan/jadwal/ubah'
      fullPath: '/latihan/jadwal/ubah'
      preLoaderRoute: typeof LatihanJadwalUbahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perenang_/$id_/laporan': {
      id: '/perenang_/$id_/laporan'
      path: '/perenang/$id/laporan'
      fullPath: '/perenang/$id/laporan'
      preLoaderRoute: typeof PerenangIdLaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktivitasRoute: AktivitasRoute,
  EventRoute: EventRoute,
  LatihanRoute: LatihanRoute,
  LoginRoute: LoginRoute,
  PengumumanRoute: PengumumanRoute,
  PerenangRoute: PerenangRoute,
  TerimaRoute: TerimaRoute,
  UndanganRoute: UndanganRoute,
  EventIdRoute: EventIdRoute,
  LatihanIdRoute: LatihanIdRoute,
  LatihanBaruRoute: LatihanBaruRoute,
  LatihanJadwalRoute: LatihanJadwalRoute,
  PengumumanIdRoute: PengumumanIdRoute,
  PerenangIdRoute: PerenangIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  LatihanIdUbahRoute: LatihanIdUbahRoute,
  LatihanJadwalUbahRoute: LatihanJadwalUbahRoute,
  PerenangIdLaporanRoute: PerenangIdLaporanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
